name: calms_parent_latest
description: A new Flutter project.
publish_to: "none"
version: 3.1.4+25

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dependencies:
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
  syncfusion_flutter_charts: ^21.1.41
  table_calendar: ^2.2.1
  encrypt: ^5.0.1
  crypto: ^3.0.1
  hex: ^0.2.0
  hash_password: ^0.0.3
  http: ^0.13.4
  progress_dialog: ^1.2.4
  shared_preferences: ^2.0.13
  syncfusion_flutter_calendar: ^21.1.41
  card_swiper: ^1.0.4
  wheel_chooser: ^1.0.0
  scroll_edge_listener: ^0.1.1
  rflutter_alert: ^2.0.4
  device_info_plus: ^8.2.0
  provider: ^6.0.2
  modal_bottom_sheet: ^2.0.0
  badges: ^2.0.2
  #firebase_messaging: ^14.3.0
  #firebase_core_dart: ^0.1.1
  #firebase_core: ^2.8.0
  #flutter_local_notifications: ^13.0.0
  sn_progress_dialog: ^1.0.3
  connectivity_plus: ^2.2.1
  footer: ^0.0.4
  geolocator: ^9.0.2
  google_maps_flutter: ^2.1.4
  flutter_polyline_points: ^1.0.0
  awesome_select: ^6.0.0
  sticky_headers: "^0.1.8"
  dropdown_button2: ^1.4.0
  super_tooltip: ^1.0.1
  just_the_tooltip: ^0.0.11+2
  permission_handler: ^10.0.0
  expandable_fab_menu: ^0.0.1
  expendable_fab: ^0.0.3
  cached_network_image: ^3.2.3
  multi_select_flutter: ^4.1.3
  fullscreen: ^1.0.3
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  device_info_plus_web: ^0.0.1
  platform_device_id: ^1.0.1
  flutter_widget_from_html: ^0.10.0
  html_unescape: ^2.0.0
  flutter_expandable_fab: ^1.8.1
  webview_flutter: ^4.2.4
  collection: ^1.17.0
  html: ^0.15.4
  url_launcher: ^6.1.11
  back_button_interceptor: ^6.0.2
  focus_detector: ^2.0.1
  mobile_scanner: ^3.5.0

#dependency_overrides:
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: robotoBlack
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
